Add preview option
x-motemen/blogsync pull request #104
Opened 2023-10-20 10:07 UTC by Mahito

entryHeader に以下のフィールドを追加
- PreviewURL
- IsDraft

2023-10-20 10:49 UTC, Songmu commented
早速ありがとうございます！
IsPreviewはフィールドとしてもFrontMatterでもなくてよいかと思いました。(Preview URLの有無で自明なので)

とりあえずは、「Draft時には自動的にPreviewURLを発行する」というシンプルな仕様で良いかと思います。

もし、PreviewURLを発行したくないという要望が来た時点でどのようにするかを考えるのが良いかと思っていますし、個人的にはあまり対応の必要性は感じていません。

また、仮に将来的に対応するとしても、entryHeader に情報を増やすよりかは、コマンドラインオプションで `--no-preview` などを追加するほうが良いかなぁとも思っています。

なので、とりあえずは `IsPreview` を削ってもらいたいです。

2023-10-20 12:52 UTC, Songmu requested changes

2023-10-20 12:52 UTC, Songmu commented on entry.go
> +			PreviewURL: previewLink.Href,
PreviewLinkはnilableだと思うので、nilチェックするようにして下さい。
(調べてはいませんが、公開後のエントリーや、はてなブログ管理画面から作られた下書きでpreviewを発行していないものは link rel="preview" がない気がしますし、その可能性はケアしておいたほうが良いと思います

2023-10-21 06:26 UTC, Mahito commented on entry.go
> +			PreviewURL: previewLink.Href,
コメントありがとうございます。

実装時に PreviewLink が nil のケースは考えたのですが、コメントにあるように公開後や preview=no の場合 PreviewLink に nil が来るケースはあると思います。
しかし、alternateLink や EditLink と同様に nil が来た際エラーとして return するべきかというと、PreviewLink の場合 nil のケースは上記のように正常動作として許容されるべきかと思います。結果、nil チエックをしたとして、そのチェックの結果何を処理すべきかが思いつかずとりあえずひとまず nil チェックを飛ばした次第です。

PreviewLink が nil の場合の処理どうしましょうか・・・？

2023-10-21 06:38 UTC, Songmu commented on entry.go
> +			PreviewURL: previewLink.Href,
確認ありがとうございます。previewLinkがnilの場合、previewLink.Hrefにアクセスするとnil pointer exceptionが起きてしまうので、ハンドリングは必要です。
`entryHeader.PreviewURL` をomitemptyに設定してもらっているので、プレビューリンクがない場合に空文字列を指定するという方針で良いのではないでしょうか。空文字列を渡しておけばプFrontMatterに書かれなくなるので。

2023-10-21 11:40 UTC, Mahito commented on entry.go
> +			PreviewURL: previewLink.Href,
previewLink.Href のこと忘れてましたので nil チェック追加しました 🙇

2023-10-21 13:43 UTC, Songmu commented
Thank you!

2023-10-21 13:43 UTC, merged