Update/post url
x-motemen/blogsync pull request #58
Opened 2023-01-17 07:42 UTC by halkt

2023-01-17 09:40 UTC, Songmu requested changes
ありがとうございます！これは大事な変更ですね。
一点お願いしたいのですが、設定名は単にownerで良いと思うので、その点だけ変更してもらえますでしょうか。

2023-01-17 13:28 UTC, halkt commented
blogであることは自明だったのでownerに統一しました!

2023-01-25 10:29 UTC, Songmu approved these changes

2023-01-25 10:30 UTC, Songmu commented
あれ、これマージしたつもりになっていました…。すみません。とりこみますね。

2023-01-25 10:30 UTC, merged