Marketplaceに公開するためのアクションの作成
x-motemen/blogsync pull request #63
Opened 2023-04-13 06:58 UTC by theoremoon

#62 の通り、blogsyncの公式アクションがGitHub Marketplaceにあって、ユーザは自分のworkflowに `uses: x-motemen/blogsync@v1` のように書くだけ、となっていると便利と思って、https://github.com/kayac/ecspresso/blob/v1/action.yml を参考に `action.yml` を作っています。

2023-04-14 16:40 UTC, Songmu commented
カスタムアクションの要望と作成までありがとうございます。
ただ、残念ながらこれでは対応しきれていないケースがあります。

- `uses: x-motemen/blogsync@v1` の `@v1`  の部分はGITREFです。なので、 v1というtagかbranchが存在している必要がありますが、blogsyncには存在しません。escpressoの場合は、 v1, v2といったブランチ名を採用しているので、 `kayac/ecspresso@v2` とすれば最新版を使えるのですが、blogsyncの場合はmasterブランチがメインブランチであるため `uses: x-motemen/blogsync@master` とする必要があるでしょう。
- `x-motemen/blogsync@v1` のようにしたい場合、個人的にはブランチ名よりタグが良いと思っているので、blogsyncのリリース時にv1タグを打ち直す(force pushする)方法が良いでしょう。
    - https://github.com/haya14busa/action-update-semver を使うと簡単です
    - https://github.com/Songmu/tagpr/blob/43d52e123cf8d55db9d602601f115f530588e2f8/.github/workflows/release.yaml#L25 このあたりを参考にしてください
    - v1ブランチ名を使いたくない理由としては、コミットと成果物の生成にタイムラグがあるからです。v1ブランチを使う場合、v1ブランチのコミットが進んでから成果物を作ることになりますが、私は先に成果物を生成してからタグを打ちたいと考えているためです。(説明が分かりづらいので理解できなかったらすみません)
- 細かい話で対応は必須ではありませんが、このactions.ymlはOSとARCHが決め打ちになっています。
    - https://github.com/Songmu/tagpr/blob/main/install.sh のようなものを置いてそれを使うのが私が最近やっている方法です
- 実は `uses: x-motemen/blogsync@master` とするだけであれば、Marketplaceに公開しなくても実行可能です。Marketplaceで検索されないだけです。
    - また、Marketplaceに公開したい場合は、action.ymlにname, description, brandingセクションが追加で必要です

このあたりもう少し整えていただいても構いません。また、僕の方で、このブランチをベースにして手直しをさせてもらうかもしれません。(このcontribution自体は残したいので)

2023-04-14 16:40 UTC, Songmu requested changes
カスタムアクションの要望と作成までありがとうございます。
ただ、残念ながらこれでは対応しきれていないケースがあります。

- `uses: x-motemen/blogsync@v1` の `@v1`  の部分はGITREFです。なので、 v1というtagかbranchが存在している必要がありますが、blogsyncには存在しません。escpressoの場合は、 v1, v2といったブランチ名を採用しているので、 `kayac/ecspresso@v2` とすれば最新版を使えるのですが、blogsyncの場合はmasterブランチがメインブランチであるため `uses: x-motemen/blogsync@master` とする必要があるでしょう。
- `x-motemen/blogsync@v1` のようにしたい場合、個人的にはブランチ名よりタグが良いと思っているので、blogsyncのリリース時にv1タグを打ち直す(force pushする)方法が良いでしょう。
    - https://github.com/haya14busa/action-update-semver を使うと簡単です
    - https://github.com/Songmu/tagpr/blob/43d52e123cf8d55db9d602601f115f530588e2f8/.github/workflows/release.yaml#L25 このあたりを参考にしてください
    - v1ブランチ名を使いたくない理由としては、コミットと成果物の生成にタイムラグがあるからです。v1ブランチを使う場合、v1ブランチのコミットが進んでから成果物を作ることになりますが、私は先に成果物を生成してからタグを打ちたいと考えているためです。(説明が分かりづらいので理解できなかったらすみません)
- 細かい話で対応は必須ではありませんが、このactions.ymlはOSとARCHが決め打ちになっています。
    - https://github.com/Songmu/tagpr/blob/main/install.sh のようなものを置いてそれを使うのが私が最近やっている方法です
- 実は `uses: x-motemen/blogsync@master` とするだけであれば、Marketplaceに公開しなくても実行可能です。Marketplaceで検索されないだけです。
    - また、Marketplaceに公開したい場合は、action.ymlにname, description, brandingセクションが追加で必要です

このあたりもう少し整えていただいても構いません。また、僕の方で、このブランチをベースにして手直しをさせてもらうかもしれません。(このcontribution自体は残したいので)

2023-04-14 17:14 UTC, merged

2023-04-14 17:38 UTC, Songmu commented
v0.13.2 としてリリースしました。試してみてください

2023-04-18 02:06 UTC, theoremoon commented
#64 とリリースありがとうございました。早速便利に使わせてもらっています！